# Generated by Django 4.0.3 on 2022-05-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BehindTheScenes',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Manipulation',
        ),
        migrations.DeleteModel(
            name='ModelsAndFashion',
        ),
        migrations.DeleteModel(
            name='Monument',
        ),
        migrations.DeleteModel(
            name='Perfume',
        ),
        migrations.DeleteModel(
            name='Portrait',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShortMovies',
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
